#RehabCfg
dataset_root: '/data/wmucha/datasets/rehab_dataset/Dataset'
seed_num: 42
batch_size: 8
num_workers: 32
max_epochs: 500
lr: 0.01
device: 6
num_frames: 16
use_scheduler: True
scheduler_milestones: [10, 15]
img_size: [224,224]
model_type: 'MViT_V2s'
load_checkpoint: False
checkpoint_name: checkpoints/weights.pth
optimizer_type: 'AdamW'
early_stopping: 25
cross_subject: False
subject: Subject_2
task: exercise_recognition
project_name: Rehab_Action_Recognition
bacbone_freeze: True